export const CONST = {
  BASE_URL_API: `${process.env.REACT_APP_BASE_URL_API}/v1`,
  EMAILJS_SERVICE_ID: process.env.REACT_APP_EMAILJS_SERVICE_ID,
  EMAILJS_PUBLIC_KEY: process.env.REACT_APP_EMAILJS_PUBLIC_KEY,
  EMAILJS_TEMPLATE_ACC: process.env.REACT_APP_EMAILJS_TEMPLATE_ACC,
  EMAILJS_TEMPLATE_REJECT: process.env.REACT_APP_EMAILJS_TEMPLATE_REJECT,
}